# List of available animations:
# - GROWTH_EVERY_BLOCK
# - GROWTH
# - ENCHANTED_FRAME
# - STRIKE
animations:
  FIRE:
    type: ENCHANTED_FRAME
    time: 100
  NETHER_PAIR:
    type: ENCHANTED_FRAME
    time: 100
  END_PLATFORM:
    type: ENCHANTED_FRAME
    time: 100